name: reading_where
description: "Reading around US and The World"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.3.2
  path: 1.9.0
  path_provider: 2.0.15
  get_it: 7.6.0
  flutter_svg: 2.0.0+1
  cupertino_icons: ^1.0.6
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/country_flags_svg/
   - assets/images/country_flags_png/
   - assets/images/state_flags/

